spring:
    application:
        name: linear
    datasource:
        url: jdbc:h2:file:./database
        driverClassName: org.h2.Driver
        username: sa
        password: password
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update